# Generated by Django 4.1.7 on 2023-04-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("KaraoKeySite", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voice_record", models.FileField(upload_to="records")),
            ],
        ),
    ]
